// Mocks generated by Mockito 5.1.0 from annotations
// in my_flutter_playground/test/search_test.dart.
// Do not manually edit this file.

// Dart imports:
import 'dart:async' as _i4;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:my_flutter_playground/api/search_api.dart' as _i3;
import 'package:my_flutter_playground/data/search_result.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSearchResult_0 extends _i1.Fake implements _i2.SearchResult {}

/// A class which mocks [SearchApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchApi extends _i1.Mock implements _i3.SearchApi {
  MockSearchApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SearchResult> search(String? query, int? page) =>
      (super.noSuchMethod(Invocation.method(#search, [query, page]),
              returnValue:
                  Future<_i2.SearchResult>.value(_FakeSearchResult_0()))
          as _i4.Future<_i2.SearchResult>);
}
